a = [{'express_data': [{'MAX_NORMALIZED_INTENSITY': '4.431343061057062', 'EXPERIMENT_SCOPE_NAME': '', 'SAMPLE_NAME': '',
                        'TISSUE_NAME': 'blood platelet', 'SAMPLES': 2, 'TISSUE_SAP_SYNONYM': 'circulatory_system',
                        'TISSUE_ID': 'BTO:0000132', 'UNIQUE_IDENTIFIER': 'O96028', 'PROJECT_STATUS': '',
                        'SAMPLE_ID': -1, 'MIN_NORMALIZED_INTENSITY': '3.973373101474299',
                        'NORMALIZED_INTENSITY': '4.20235808126568', 'PROJECT_NAME': '', '__metadata': {
        'uri': "http://www.proteomicsdb.org/proteomicsdb/logic/api/proteinexpression.xsodata/CA_EXPRESSION_PROFILE_API('68990852455060601')",
        'type': 'proteomicsdb.logic.api.proteinexpression.CA_EXPRESSION_PROFILE_APIType'}, 'EXPERIMENT_ID': -1,
                        'PROJECT_ID': -1, 'EXPERIMENT_NAME': '', 'EXPERIMENT_SCOPE': '',
                        'UNNORMALIZED_INTENSITY': '5.121757118543908', 'AFFINITY_PURIFICATION': ''},
                       {'MAX_NORMALIZED_INTENSITY': '3.632427843126236', 'EXPERIMENT_SCOPE_NAME': '', 'SAMPLE_NAME': '',
                        'TISSUE_NAME': 'brain', 'SAMPLES': 1, 'TISSUE_SAP_SYNONYM': 'brain', 'TISSUE_ID': 'BTO:0000142',
                        'UNIQUE_IDENTIFIER': 'O96028', 'PROJECT_STATUS': '', 'SAMPLE_ID': -1,
                        'MIN_NORMALIZED_INTENSITY': '3.632427843126236', 'NORMALIZED_INTENSITY': '3.632427843126236',
                        'PROJECT_NAME': '', '__metadata': {
                           'uri': "http://www.proteomicsdb.org/proteomicsdb/logic/api/proteinexpression.xsodata/CA_EXPRESSION_PROFILE_API('68990852455060602')",
                           'type': 'proteomicsdb.logic.api.proteinexpression.CA_EXPRESSION_PROFILE_APIType'},
                        'EXPERIMENT_ID': -1, 'PROJECT_ID': -1, 'EXPERIMENT_NAME': '', 'EXPERIMENT_SCOPE': '',
                        'UNNORMALIZED_INTENSITY': '4.43470011743423', 'AFFINITY_PURIFICATION': ''},
                       {'MAX_NORMALIZED_INTENSITY': '4.39065632745664', 'EXPERIMENT_SCOPE_NAME': '', 'SAMPLE_NAME': '',
                        'TISSUE_NAME': 'colon', 'SAMPLES': 2, 'TISSUE_SAP_SYNONYM': 'colon', 'TISSUE_ID': 'BTO:0000269',
                        'UNIQUE_IDENTIFIER': 'O96028', 'PROJECT_STATUS': '', 'SAMPLE_ID': -1,
                        'MIN_NORMALIZED_INTENSITY': '3.638599673272687', 'NORMALIZED_INTENSITY': '4.014628000364664',
                        'PROJECT_NAME': '', '__metadata': {
                           'uri': "http://www.proteomicsdb.org/proteomicsdb/logic/api/proteinexpression.xsodata/CA_EXPRESSION_PROFILE_API('68990852455060603')",
                           'type': 'proteomicsdb.logic.api.proteinexpression.CA_EXPRESSION_PROFILE_APIType'},
                        'EXPERIMENT_ID': -1, 'PROJECT_ID': -1, 'EXPERIMENT_NAME': '', 'EXPERIMENT_SCOPE': '',
                        'UNNORMALIZED_INTENSITY': '4.139091763295253', 'AFFINITY_PURIFICATION': ''},
                       {'MAX_NORMALIZED_INTENSITY': '2.953219841043003', 'EXPERIMENT_SCOPE_NAME': '', 'SAMPLE_NAME': '',
                        'TISSUE_NAME': 'cytotoxic T-lymphocyte', 'SAMPLES': 1,
                        'TISSUE_SAP_SYNONYM': 'circulatory_system', 'TISSUE_ID': 'BTO:0000289',
                        'UNIQUE_IDENTIFIER': 'O96028', 'PROJECT_STATUS': '', 'SAMPLE_ID': -1,
                        'MIN_NORMALIZED_INTENSITY': '2.953219841043003', 'NORMALIZED_INTENSITY': '2.953219841043003',
                        'PROJECT_NAME': '', '__metadata': {
                           'uri': "http://www.proteomicsdb.org/proteomicsdb/logic/api/proteinexpression.xsodata/CA_EXPRESSION_PROFILE_API('68990852455060604')",
                           'type': 'proteomicsdb.logic.api.proteinexpression.CA_EXPRESSION_PROFILE_APIType'},
                        'EXPERIMENT_ID': -1, 'PROJECT_ID': -1, 'EXPERIMENT_NAME': '', 'EXPERIMENT_SCOPE': '',
                        'UNNORMALIZED_INTENSITY': '4.333240175027596', 'AFFINITY_PURIFICATION': ''},
                       {'MAX_NORMALIZED_INTENSITY': '3.555547432498772', 'EXPERIMENT_SCOPE_NAME': '', 'SAMPLE_NAME': '',
                        'TISSUE_NAME': 'heart', 'SAMPLES': 2, 'TISSUE_SAP_SYNONYM': 'heart', 'TISSUE_ID': 'BTO:0000562',
                        'UNIQUE_IDENTIFIER': 'O96028', 'PROJECT_STATUS': '', 'SAMPLE_ID': -1,
                        'MIN_NORMALIZED_INTENSITY': '2.743822590945711', 'NORMALIZED_INTENSITY': '3.149685011722242',
                        'PROJECT_NAME': '', '__metadata': {
                           'uri': "http://www.proteomicsdb.org/proteomicsdb/logic/api/proteinexpression.xsodata/CA_EXPRESSION_PROFILE_API('68990852455060605')",
                           'type': 'proteomicsdb.logic.api.proteinexpression.CA_EXPRESSION_PROFILE_APIType'},
                        'EXPERIMENT_ID': -1, 'PROJECT_ID': -1, 'EXPERIMENT_NAME': '', 'EXPERIMENT_SCOPE': '',
                        'UNNORMALIZED_INTENSITY': '4.552358851462124', 'AFFINITY_PURIFICATION': ''},
                       {'MAX_NORMALIZED_INTENSITY': '3.428389961432673', 'EXPERIMENT_SCOPE_NAME': '', 'SAMPLE_NAME': '',
                        'TISSUE_NAME': 'ovary', 'SAMPLES': 1, 'TISSUE_SAP_SYNONYM': 'ovary', 'TISSUE_ID': 'BTO:0000975',
                        'UNIQUE_IDENTIFIER': 'O96028', 'PROJECT_STATUS': '', 'SAMPLE_ID': -1,
                        'MIN_NORMALIZED_INTENSITY': '3.428389961432673', 'NORMALIZED_INTENSITY': '3.428389961432673',
                        'PROJECT_NAME': '', '__metadata': {
                           'uri': "http://www.proteomicsdb.org/proteomicsdb/logic/api/proteinexpression.xsodata/CA_EXPRESSION_PROFILE_API('68990852455060606')",
                           'type': 'proteomicsdb.logic.api.proteinexpression.CA_EXPRESSION_PROFILE_APIType'},
                        'EXPERIMENT_ID': -1, 'PROJECT_ID': -1, 'EXPERIMENT_NAME': '', 'EXPERIMENT_SCOPE': '',
                        'UNNORMALIZED_INTENSITY': '4.291101112994191', 'AFFINITY_PURIFICATION': ''},
                       {'MAX_NORMALIZED_INTENSITY': '4.991208025873466', 'EXPERIMENT_SCOPE_NAME': '', 'SAMPLE_NAME': '',
                        'TISSUE_NAME': 'rectum', 'SAMPLES': 1, 'TISSUE_SAP_SYNONYM': 'rectum',
                        'TISSUE_ID': 'BTO:0001158', 'UNIQUE_IDENTIFIER': 'O96028', 'PROJECT_STATUS': '',
                        'SAMPLE_ID': -1, 'MIN_NORMALIZED_INTENSITY': '4.991208025873466',
                        'NORMALIZED_INTENSITY': '4.991208025873466', 'PROJECT_NAME': '', '__metadata': {
                           'uri': "http://www.proteomicsdb.org/proteomicsdb/logic/api/proteinexpression.xsodata/CA_EXPRESSION_PROFILE_API('68990852455060607')",
                           'type': 'proteomicsdb.logic.api.proteinexpression.CA_EXPRESSION_PROFILE_APIType'},
                        'EXPERIMENT_ID': -1, 'PROJECT_ID': -1, 'EXPERIMENT_NAME': '', 'EXPERIMENT_SCOPE': '',
                        'UNNORMALIZED_INTENSITY': '4.639397787420427', 'AFFINITY_PURIFICATION': ''},
                       {'MAX_NORMALIZED_INTENSITY': '3.479923090424131', 'EXPERIMENT_SCOPE_NAME': '', 'SAMPLE_NAME': '',
                        'TISSUE_NAME': 'proximal fluid (coronary sinus)', 'SAMPLES': 1,
                        'TISSUE_SAP_SYNONYM': 'proximal_fluid', 'TISSUE_ID': 'PDB:200000',
                        'UNIQUE_IDENTIFIER': 'O96028', 'PROJECT_STATUS': '', 'SAMPLE_ID': -1,
                        'MIN_NORMALIZED_INTENSITY': '3.479923090424131', 'NORMALIZED_INTENSITY': '3.479923090424131',
                        'PROJECT_NAME': '', '__metadata': {
                           'uri': "http://www.proteomicsdb.org/proteomicsdb/logic/api/proteinexpression.xsodata/CA_EXPRESSION_PROFILE_API('68990852455060608')",
                           'type': 'proteomicsdb.logic.api.proteinexpression.CA_EXPRESSION_PROFILE_APIType'},
                        'EXPERIMENT_ID': -1, 'PROJECT_ID': -1, 'EXPERIMENT_NAME': '', 'EXPERIMENT_SCOPE': '',
                        'UNNORMALIZED_INTENSITY': '4.524066966218274', 'AFFINITY_PURIFICATION': ''}],
      'entrez_id': '7468', 'uniprotkb_ac': 'O96028'}]
b = {'express_data': [{'MAX_NORMALIZED_INTENSITY': '4.431343061057062', 'EXPERIMENT_SCOPE_NAME': '', 'SAMPLE_NAME': '',
                       'TISSUE_NAME': 'blood platelet', 'SAMPLES': 2, 'TISSUE_SAP_SYNONYM': 'circulatory_system',
                       'TISSUE_ID': 'BTO:0000132', 'UNIQUE_IDENTIFIER': 'O96028', 'PROJECT_STATUS': '', 'SAMPLE_ID': -1,
                       'MIN_NORMALIZED_INTENSITY': '3.973373101474299', 'NORMALIZED_INTENSITY': '4.20235808126568',
                       'PROJECT_NAME': '', '__metadata': {
        'uri': "http://www.proteomicsdb.org/proteomicsdb/logic/api/proteinexpression.xsodata/CA_EXPRESSION_PROFILE_API('68990852455060601')",
        'type': 'proteomicsdb.logic.api.proteinexpression.CA_EXPRESSION_PROFILE_APIType'}, 'EXPERIMENT_ID': -1,
                       'PROJECT_ID': -1, 'EXPERIMENT_NAME': '', 'EXPERIMENT_SCOPE': '',
                       'UNNORMALIZED_INTENSITY': '5.121757118543908', 'AFFINITY_PURIFICATION': ''},
                      {'MAX_NORMALIZED_INTENSITY': '3.632427843126236', 'EXPERIMENT_SCOPE_NAME': '', 'SAMPLE_NAME': '',
                       'TISSUE_NAME': 'brain', 'SAMPLES': 1, 'TISSUE_SAP_SYNONYM': 'brain', 'TISSUE_ID': 'BTO:0000142',
                       'UNIQUE_IDENTIFIER': 'O96028', 'PROJECT_STATUS': '', 'SAMPLE_ID': -1,
                       'MIN_NORMALIZED_INTENSITY': '3.632427843126236', 'NORMALIZED_INTENSITY': '3.632427843126236',
                       'PROJECT_NAME': '', '__metadata': {
                          'uri': "http://www.proteomicsdb.org/proteomicsdb/logic/api/proteinexpression.xsodata/CA_EXPRESSION_PROFILE_API('68990852455060602')",
                          'type': 'proteomicsdb.logic.api.proteinexpression.CA_EXPRESSION_PROFILE_APIType'},
                       'EXPERIMENT_ID': -1, 'PROJECT_ID': -1, 'EXPERIMENT_NAME': '', 'EXPERIMENT_SCOPE': '',
                       'UNNORMALIZED_INTENSITY': '4.43470011743423', 'AFFINITY_PURIFICATION': ''},
                      {'MAX_NORMALIZED_INTENSITY': '4.39065632745664', 'EXPERIMENT_SCOPE_NAME': '', 'SAMPLE_NAME': '',
                       'TISSUE_NAME': 'colon', 'SAMPLES': 2, 'TISSUE_SAP_SYNONYM': 'colon', 'TISSUE_ID': 'BTO:0000269',
                       'UNIQUE_IDENTIFIER': 'O96028', 'PROJECT_STATUS': '', 'SAMPLE_ID': -1,
                       'MIN_NORMALIZED_INTENSITY': '3.638599673272687', 'NORMALIZED_INTENSITY': '4.014628000364664',
                       'PROJECT_NAME': '', '__metadata': {
                          'uri': "http://www.proteomicsdb.org/proteomicsdb/logic/api/proteinexpression.xsodata/CA_EXPRESSION_PROFILE_API('68990852455060603')",
                          'type': 'proteomicsdb.logic.api.proteinexpression.CA_EXPRESSION_PROFILE_APIType'},
                       'EXPERIMENT_ID': -1, 'PROJECT_ID': -1, 'EXPERIMENT_NAME': '', 'EXPERIMENT_SCOPE': '',
                       'UNNORMALIZED_INTENSITY': '4.139091763295253', 'AFFINITY_PURIFICATION': ''},
                      {'MAX_NORMALIZED_INTENSITY': '2.953219841043003', 'EXPERIMENT_SCOPE_NAME': '', 'SAMPLE_NAME': '',
                       'TISSUE_NAME': 'cytotoxic T-lymphocyte', 'SAMPLES': 1,
                       'TISSUE_SAP_SYNONYM': 'circulatory_system', 'TISSUE_ID': 'BTO:0000289',
                       'UNIQUE_IDENTIFIER': 'O96028', 'PROJECT_STATUS': '', 'SAMPLE_ID': -1,
                       'MIN_NORMALIZED_INTENSITY': '2.953219841043003', 'NORMALIZED_INTENSITY': '2.953219841043003',
                       'PROJECT_NAME': '', '__metadata': {
                          'uri': "http://www.proteomicsdb.org/proteomicsdb/logic/api/proteinexpression.xsodata/CA_EXPRESSION_PROFILE_API('68990852455060604')",
                          'type': 'proteomicsdb.logic.api.proteinexpression.CA_EXPRESSION_PROFILE_APIType'},
                       'EXPERIMENT_ID': -1, 'PROJECT_ID': -1, 'EXPERIMENT_NAME': '', 'EXPERIMENT_SCOPE': '',
                       'UNNORMALIZED_INTENSITY': '4.333240175027596', 'AFFINITY_PURIFICATION': ''},
                      {'MAX_NORMALIZED_INTENSITY': '3.555547432498772', 'EXPERIMENT_SCOPE_NAME': '', 'SAMPLE_NAME': '',
                       'TISSUE_NAME': 'heart', 'SAMPLES': 2, 'TISSUE_SAP_SYNONYM': 'heart', 'TISSUE_ID': 'BTO:0000562',
                       'UNIQUE_IDENTIFIER': 'O96028', 'PROJECT_STATUS': '', 'SAMPLE_ID': -1,
                       'MIN_NORMALIZED_INTENSITY': '2.743822590945711', 'NORMALIZED_INTENSITY': '3.149685011722242',
                       'PROJECT_NAME': '', '__metadata': {
                          'uri': "http://www.proteomicsdb.org/proteomicsdb/logic/api/proteinexpression.xsodata/CA_EXPRESSION_PROFILE_API('68990852455060605')",
                          'type': 'proteomicsdb.logic.api.proteinexpression.CA_EXPRESSION_PROFILE_APIType'},
                       'EXPERIMENT_ID': -1, 'PROJECT_ID': -1, 'EXPERIMENT_NAME': '', 'EXPERIMENT_SCOPE': '',
                       'UNNORMALIZED_INTENSITY': '4.552358851462124', 'AFFINITY_PURIFICATION': ''},
                      {'MAX_NORMALIZED_INTENSITY': '3.428389961432673', 'EXPERIMENT_SCOPE_NAME': '', 'SAMPLE_NAME': '',
                       'TISSUE_NAME': 'ovary', 'SAMPLES': 1, 'TISSUE_SAP_SYNONYM': 'ovary', 'TISSUE_ID': 'BTO:0000975',
                       'UNIQUE_IDENTIFIER': 'O96028', 'PROJECT_STATUS': '', 'SAMPLE_ID': -1,
                       'MIN_NORMALIZED_INTENSITY': '3.428389961432673', 'NORMALIZED_INTENSITY': '3.428389961432673',
                       'PROJECT_NAME': '', '__metadata': {
                          'uri': "http://www.proteomicsdb.org/proteomicsdb/logic/api/proteinexpression.xsodata/CA_EXPRESSION_PROFILE_API('68990852455060606')",
                          'type': 'proteomicsdb.logic.api.proteinexpression.CA_EXPRESSION_PROFILE_APIType'},
                       'EXPERIMENT_ID': -1, 'PROJECT_ID': -1, 'EXPERIMENT_NAME': '', 'EXPERIMENT_SCOPE': '',
                       'UNNORMALIZED_INTENSITY': '4.291101112994191', 'AFFINITY_PURIFICATION': ''},
                      {'MAX_NORMALIZED_INTENSITY': '4.991208025873466', 'EXPERIMENT_SCOPE_NAME': '', 'SAMPLE_NAME': '',
                       'TISSUE_NAME': 'rectum', 'SAMPLES': 1, 'TISSUE_SAP_SYNONYM': 'rectum',
                       'TISSUE_ID': 'BTO:0001158', 'UNIQUE_IDENTIFIER': 'O96028', 'PROJECT_STATUS': '', 'SAMPLE_ID': -1,
                       'MIN_NORMALIZED_INTENSITY': '4.991208025873466', 'NORMALIZED_INTENSITY': '4.991208025873466',
                       'PROJECT_NAME': '', '__metadata': {
                          'uri': "http://www.proteomicsdb.org/proteomicsdb/logic/api/proteinexpression.xsodata/CA_EXPRESSION_PROFILE_API('68990852455060607')",
                          'type': 'proteomicsdb.logic.api.proteinexpression.CA_EXPRESSION_PROFILE_APIType'},
                       'EXPERIMENT_ID': -1, 'PROJECT_ID': -1, 'EXPERIMENT_NAME': '', 'EXPERIMENT_SCOPE': '',
                       'UNNORMALIZED_INTENSITY': '4.639397787420427', 'AFFINITY_PURIFICATION': ''},
                      {'MAX_NORMALIZED_INTENSITY': '3.479923090424131', 'EXPERIMENT_SCOPE_NAME': '', 'SAMPLE_NAME': '',
                       'TISSUE_NAME': 'proximal fluid (coronary sinus)', 'SAMPLES': 1,
                       'TISSUE_SAP_SYNONYM': 'proximal_fluid', 'TISSUE_ID': 'PDB:200000', 'UNIQUE_IDENTIFIER': 'O96028',
                       'PROJECT_STATUS': '', 'SAMPLE_ID': -1, 'MIN_NORMALIZED_INTENSITY': '3.479923090424131',
                       'NORMALIZED_INTENSITY': '3.479923090424131', 'PROJECT_NAME': '', '__metadata': {
                          'uri': "http://www.proteomicsdb.org/proteomicsdb/logic/api/proteinexpression.xsodata/CA_EXPRESSION_PROFILE_API('68990852455060608')",
                          'type': 'proteomicsdb.logic.api.proteinexpression.CA_EXPRESSION_PROFILE_APIType'},
                       'EXPERIMENT_ID': -1, 'PROJECT_ID': -1, 'EXPERIMENT_NAME': '', 'EXPERIMENT_SCOPE': '',
                       'UNNORMALIZED_INTENSITY': '4.524066966218274', 'AFFINITY_PURIFICATION': ''}],
     'entrez_id': '7468', 'uniprotkb_ac': 'O96028'}
res_list = [[{'MAX_NORMALIZED_INTENSITY': '4.431343061057062', 'EXPERIMENT_SCOPE_NAME': '', 'SAMPLE_NAME': '',
              'TISSUE_NAME': 'blood platelet', 'SAMPLES': 2, 'TISSUE_SAP_SYNONYM': 'circulatory_system',
              'TISSUE_ID': 'BTO:0000132', 'UNIQUE_IDENTIFIER': 'O96028', 'PROJECT_STATUS': '', 'SAMPLE_ID': -1,
              'MIN_NORMALIZED_INTENSITY': '3.973373101474299', 'NORMALIZED_INTENSITY': '4.20235808126568',
              'PROJECT_NAME': '', '__metadata': {
        'uri': "http://www.proteomicsdb.org/proteomicsdb/logic/api/proteinexpression.xsodata/CA_EXPRESSION_PROFILE_API('68990852455060601')",
        'type': 'proteomicsdb.logic.api.proteinexpression.CA_EXPRESSION_PROFILE_APIType'}, 'EXPERIMENT_ID': -1,
              'PROJECT_ID': -1, 'EXPERIMENT_NAME': '', 'EXPERIMENT_SCOPE': '',
              'UNNORMALIZED_INTENSITY': '5.121757118543908', 'AFFINITY_PURIFICATION': ''},
             {'MAX_NORMALIZED_INTENSITY': '3.632427843126236', 'EXPERIMENT_SCOPE_NAME': '', 'SAMPLE_NAME': '',
              'TISSUE_NAME': 'brain', 'SAMPLES': 1, 'TISSUE_SAP_SYNONYM': 'brain', 'TISSUE_ID': 'BTO:0000142',
              'UNIQUE_IDENTIFIER': 'O96028', 'PROJECT_STATUS': '', 'SAMPLE_ID': -1,
              'MIN_NORMALIZED_INTENSITY': '3.632427843126236', 'NORMALIZED_INTENSITY': '3.632427843126236',
              'PROJECT_NAME': '', '__metadata': {
                 'uri': "http://www.proteomicsdb.org/proteomicsdb/logic/api/proteinexpression.xsodata/CA_EXPRESSION_PROFILE_API('68990852455060602')",
                 'type': 'proteomicsdb.logic.api.proteinexpression.CA_EXPRESSION_PROFILE_APIType'}, 'EXPERIMENT_ID': -1,
              'PROJECT_ID': -1, 'EXPERIMENT_NAME': '', 'EXPERIMENT_SCOPE': '',
              'UNNORMALIZED_INTENSITY': '4.43470011743423', 'AFFINITY_PURIFICATION': ''},
             {'MAX_NORMALIZED_INTENSITY': '4.39065632745664', 'EXPERIMENT_SCOPE_NAME': '', 'SAMPLE_NAME': '',
              'TISSUE_NAME': 'colon', 'SAMPLES': 2, 'TISSUE_SAP_SYNONYM': 'colon', 'TISSUE_ID': 'BTO:0000269',
              'UNIQUE_IDENTIFIER': 'O96028', 'PROJECT_STATUS': '', 'SAMPLE_ID': -1,
              'MIN_NORMALIZED_INTENSITY': '3.638599673272687', 'NORMALIZED_INTENSITY': '4.014628000364664',
              'PROJECT_NAME': '', '__metadata': {
                 'uri': "http://www.proteomicsdb.org/proteomicsdb/logic/api/proteinexpression.xsodata/CA_EXPRESSION_PROFILE_API('68990852455060603')",
                 'type': 'proteomicsdb.logic.api.proteinexpression.CA_EXPRESSION_PROFILE_APIType'}, 'EXPERIMENT_ID': -1,
              'PROJECT_ID': -1, 'EXPERIMENT_NAME': '', 'EXPERIMENT_SCOPE': '',
              'UNNORMALIZED_INTENSITY': '4.139091763295253', 'AFFINITY_PURIFICATION': ''},
             {'MAX_NORMALIZED_INTENSITY': '2.953219841043003', 'EXPERIMENT_SCOPE_NAME': '', 'SAMPLE_NAME': '',
              'TISSUE_NAME': 'cytotoxic T-lymphocyte', 'SAMPLES': 1, 'TISSUE_SAP_SYNONYM': 'circulatory_system',
              'TISSUE_ID': 'BTO:0000289', 'UNIQUE_IDENTIFIER': 'O96028', 'PROJECT_STATUS': '', 'SAMPLE_ID': -1,
              'MIN_NORMALIZED_INTENSITY': '2.953219841043003', 'NORMALIZED_INTENSITY': '2.953219841043003',
              'PROJECT_NAME': '', '__metadata': {
                 'uri': "http://www.proteomicsdb.org/proteomicsdb/logic/api/proteinexpression.xsodata/CA_EXPRESSION_PROFILE_API('68990852455060604')",
                 'type': 'proteomicsdb.logic.api.proteinexpression.CA_EXPRESSION_PROFILE_APIType'}, 'EXPERIMENT_ID': -1,
              'PROJECT_ID': -1, 'EXPERIMENT_NAME': '', 'EXPERIMENT_SCOPE': '',
              'UNNORMALIZED_INTENSITY': '4.333240175027596', 'AFFINITY_PURIFICATION': ''},
             {'MAX_NORMALIZED_INTENSITY': '3.555547432498772', 'EXPERIMENT_SCOPE_NAME': '', 'SAMPLE_NAME': '',
              'TISSUE_NAME': 'heart', 'SAMPLES': 2, 'TISSUE_SAP_SYNONYM': 'heart', 'TISSUE_ID': 'BTO:0000562',
              'UNIQUE_IDENTIFIER': 'O96028', 'PROJECT_STATUS': '', 'SAMPLE_ID': -1,
              'MIN_NORMALIZED_INTENSITY': '2.743822590945711', 'NORMALIZED_INTENSITY': '3.149685011722242',
              'PROJECT_NAME': '', '__metadata': {
                 'uri': "http://www.proteomicsdb.org/proteomicsdb/logic/api/proteinexpression.xsodata/CA_EXPRESSION_PROFILE_API('68990852455060605')",
                 'type': 'proteomicsdb.logic.api.proteinexpression.CA_EXPRESSION_PROFILE_APIType'}, 'EXPERIMENT_ID': -1,
              'PROJECT_ID': -1, 'EXPERIMENT_NAME': '', 'EXPERIMENT_SCOPE': '',
              'UNNORMALIZED_INTENSITY': '4.552358851462124', 'AFFINITY_PURIFICATION': ''},
             {'MAX_NORMALIZED_INTENSITY': '3.428389961432673', 'EXPERIMENT_SCOPE_NAME': '', 'SAMPLE_NAME': '',
              'TISSUE_NAME': 'ovary', 'SAMPLES': 1, 'TISSUE_SAP_SYNONYM': 'ovary', 'TISSUE_ID': 'BTO:0000975',
              'UNIQUE_IDENTIFIER': 'O96028', 'PROJECT_STATUS': '', 'SAMPLE_ID': -1,
              'MIN_NORMALIZED_INTENSITY': '3.428389961432673', 'NORMALIZED_INTENSITY': '3.428389961432673',
              'PROJECT_NAME': '', '__metadata': {
                 'uri': "http://www.proteomicsdb.org/proteomicsdb/logic/api/proteinexpression.xsodata/CA_EXPRESSION_PROFILE_API('68990852455060606')",
                 'type': 'proteomicsdb.logic.api.proteinexpression.CA_EXPRESSION_PROFILE_APIType'}, 'EXPERIMENT_ID': -1,
              'PROJECT_ID': -1, 'EXPERIMENT_NAME': '', 'EXPERIMENT_SCOPE': '',
              'UNNORMALIZED_INTENSITY': '4.291101112994191', 'AFFINITY_PURIFICATION': ''},
             {'MAX_NORMALIZED_INTENSITY': '4.991208025873466', 'EXPERIMENT_SCOPE_NAME': '', 'SAMPLE_NAME': '',
              'TISSUE_NAME': 'rectum', 'SAMPLES': 1, 'TISSUE_SAP_SYNONYM': 'rectum', 'TISSUE_ID': 'BTO:0001158',
              'UNIQUE_IDENTIFIER': 'O96028', 'PROJECT_STATUS': '', 'SAMPLE_ID': -1,
              'MIN_NORMALIZED_INTENSITY': '4.991208025873466', 'NORMALIZED_INTENSITY': '4.991208025873466',
              'PROJECT_NAME': '', '__metadata': {
                 'uri': "http://www.proteomicsdb.org/proteomicsdb/logic/api/proteinexpression.xsodata/CA_EXPRESSION_PROFILE_API('68990852455060607')",
                 'type': 'proteomicsdb.logic.api.proteinexpression.CA_EXPRESSION_PROFILE_APIType'}, 'EXPERIMENT_ID': -1,
              'PROJECT_ID': -1, 'EXPERIMENT_NAME': '', 'EXPERIMENT_SCOPE': '',
              'UNNORMALIZED_INTENSITY': '4.639397787420427', 'AFFINITY_PURIFICATION': ''},
             {'MAX_NORMALIZED_INTENSITY': '3.479923090424131', 'EXPERIMENT_SCOPE_NAME': '', 'SAMPLE_NAME': '',
              'TISSUE_NAME': 'proximal fluid (coronary sinus)', 'SAMPLES': 1, 'TISSUE_SAP_SYNONYM': 'proximal_fluid',
              'TISSUE_ID': 'PDB:200000', 'UNIQUE_IDENTIFIER': 'O96028', 'PROJECT_STATUS': '', 'SAMPLE_ID': -1,
              'MIN_NORMALIZED_INTENSITY': '3.479923090424131', 'NORMALIZED_INTENSITY': '3.479923090424131',
              'PROJECT_NAME': '', '__metadata': {
                 'uri': "http://www.proteomicsdb.org/proteomicsdb/logic/api/proteinexpression.xsodata/CA_EXPRESSION_PROFILE_API('68990852455060608')",
                 'type': 'proteomicsdb.logic.api.proteinexpression.CA_EXPRESSION_PROFILE_APIType'}, 'EXPERIMENT_ID': -1,
              'PROJECT_ID': -1, 'EXPERIMENT_NAME': '', 'EXPERIMENT_SCOPE': '',
              'UNNORMALIZED_INTENSITY': '4.524066966218274', 'AFFINITY_PURIFICATION': ''}]]
